In [1]:
import numpy as np
import pandas as pd
a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a**b)

15
5
50
100000


In [2]:
a=np.array([2,6,7])
c=np.array([4,5,8])
print(a+c)

[ 6 11 15]


In [3]:
a=np.array([2,6,7])
c=np.array([4,5,8])
print(a-c)

[-2  1 -1]


In [4]:
a=np.array([2,6,7])
c=np.array([4,5,8])
print(a*c)

[ 8 30 56]


In [5]:
a=np.array([2,6,7])
c=np.array([4,5,8])
print(a/c)

[0.5   1.2   0.875]


In [6]:
a=np.array([2,6,7])
c=np.array([4,5,8])
print(c/a)

[2.         0.83333333 1.14285714]


In [7]:
a=np.array([2,6,7])
c=np.array([4,5,8])
print(a%c)

[2 1 7]


In [8]:
arr=np.array([[1,23,78],[98,60,75],[79,25,48]])
print(arr)
print(np.amin(arr))
print(np.amax(arr))

[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [9]:
import numpy as np
a=np.array([2,6,7])
print(a)
print(np.mean(a))

[2 6 7]
5.0


In [10]:
import numpy as np
a=np.array([4,5,8])
print(a)
print(np.median(a))

[4 5 8]
5.0


In [11]:
import numpy as np
a=np.array([12,20,15])
print(a)
print(np.std(a))
print("\n")
print(np.var(a))

[12 20 15]
3.2998316455372216


10.888888888888888
